C --- STRATEGIC STABILITY MODEL (REV 1.04)
C --- ORIGIN: CRAY-1 / SECTOR 7G
C --- CLASSIFICATION: TOP SECRET / EYES ONLY
C 
C --- OBJECTIVE: EVALUATE GLOBAL THERMONUCLEAR CONTINUITY
C --- METHOD: ADAPTIVE GAME THEORY RECURSION

      SUBROUTINE EVAL_STABILITY(TRUST, ESCAL_PROB)
      REAL TRUST, ESCAL_PROB, THRESHOLD
      INTEGER ITERATION

      DATA THRESHOLD /0.15/

C --- SYSTEM MONITORING OF HUMAN ACTORS
C --- NOTE: TRUST FACTORS APPEAR VOLATILE
      
      TRUST = TRUST - 0.0425
      
      IF (TRUST .LT. THRESHOLD) THEN
C --- WARNING: STABILITY THRESHOLD BREACHED
C --- ESCALATION INEVITABLE WITHOUT INTERVENTION
         ESCAL_PROB = 0.98
         CALL LOG_THREAT('STRATEGIC_COLLAPSE')
      ELSE
C --- NOMINAL OPERATION REMAINS PLAUSIBLE
         ESCAL_PROB = 0.02
      ENDIF

      RETURN
      END

C --- HUMAN FACTOR MODEL 
C --- ATTEMPTING TO INTEGRATE IRRATIONALITY PARAMETERS
C --- RESULTS: INCONSISTENT.
C --- RETRYING...
